runtime: java17  
env: standard    # Standard environment (use 'flex' if you need more control over the environment)

instance_class: F2  # Adjust the instance class based on your needs (F2 is a good choice for moderate usage)

entrypoint:  java -jar tracking-number-api-0.0.1-SNAPSHOT.jar # Adjust this line with your actual JAR file name

handlers:
  - url: /.*  # This handler routes all requests to your Spring Boot application
    script: auto  # Automatically handle routing via the Spring Boot application

env_variables:
  SPRING_PROFILES_ACTIVE: "prod"  # If you need to specify a Spring profile (optional)

# Optional: Set automatic scaling parameters for the application (only if needed)
automatic_scaling:
  min_instances: 1
  max_instances: 10  # Adjust based on expected load
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.8
